import type { Metadata } from "next"
import { Noto_Sans } from "next/font/google"
import { LayoutProps } from "@/lib/@types/props"
import { Header } from "@/ui/header"
import { Footer } from "@/ui/footer"
import "@/ui/globals.css"

const notoSans = Noto_Sans({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"],
    variable: "--font-noto-sans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en">
            <body
                className={`${notoSans.className} antialiased scroll-smooth scroll:w-1.5 track:my-1 thumb:rounded thumb:bg-black`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
