import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { PropsWithChildren } from "react"
import { RootProvider } from "fumadocs-ui/provider"
import "@/src/ui/globals.css"

const inter = Inter({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"],
    variable: "--font-inter",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<Required<PropsWithChildren>>) {
    return (
        <html className="scroll-smooth" lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} min-h-dvh flex flex-col`}>
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    )
}
