name: ci

on:
  pull_request:
    branches:
      - master
    types: closed

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test

  ci-to-development:
    if: github.event.pull_request.merged == true
    needs: [build, test]
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to development environment
        run: echo "Deploying to development environment"

  ci-to-production:
    if: github.base_ref == 'master' && startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    needs: [build, test]
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production environment
        run: echo "Deploying to production environment"
