name: ci

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run test

  deploy-to-development:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    needs: [build, test]
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to development environment
        run: echo "Deploying to development environment"

  deploy-to-production:
    if: github.event.pull_request.merged == true && github.base_ref == 'master' && startsWith(github.head_ref, 'release/')
    needs: [build, test]
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production environment
        run: echo "Deploying to production environment"
