name: ci

on:
  push:
    paths-ignore:
      - app/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4

      - name: Install package dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build:types

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4

      - name: Install package dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm test
